[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c','proto']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript','typescriptreact']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['typescriptreact','javascriptreact']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['typescript','typescriptreact','javascript','javascriptreact']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact']
